### ISSUE TITLE
how to generate the index file "tox21_index.npy"

### ISSUE THREAD

**Issue by VirtualChemist** [wsjeon92/FP2VEC#3]
Hi,
I am able to generate tox21_fp.npy and tox21_Y.npy file from the tox21.csv file.
While training the model, the input also required tox21_index.npy file.
Even though you have provided the tox21_index.npy file.
However, How did you generated this index file?
Suppose, I want to predict the toxicity of some other dataset. Then how can I get this index file?

Thanks.

**Comment by wsjeon92** [comment]
Sorry for the late reply.
I uploaded a python code "tox21_indexing.py" which generates the "tox21_index.npy" file.
Basically, "tox21_indexing.py" extracts indexes of the presence of the toxicity values (0 or 1) from the file "tox21.csv " because some of the data points are missing in the "tox21.csv" file. 
So if your custom dataset has the toxicity values in all of the data points, the index.npy file should include all the indexes. 

Please check the "tox21_indexing.py" file.

Thank you.

**Comment by VirtualChemist** [comment]
Thank you so much.
